wo_organizer:
    resource: "@WOOrganizerBundle/Controller/"
    type:     annotation
    prefix:   /admin/organizer

wo_main:
    resource: "@WOMainBundle/Controller/"
    type:     annotation
login_check:
    path:   /login_check

logout:
    path:   /logout

login:
    path: /login
    defaults: { _controller: WOMainBundle:Security:login }
#_welcome:
#    pattern:  /
#    defaults: { _controller: WOOrganizerBundle:Default:index }
#organizer_index:
#    path: /admin/organizer/{date}
#    defaults: {_controller: WOOrganizerBundle:Default:index }

homepage:
    path: /
    defaults: { _controller: WOMainBundle:Default:index }

