<?php

namespace WO\OrganizerBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
    public function getAllWithWorktimeByDate($date) {
        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare('SELECT e.*, w.timerange FROM employee e
                                        LEFT JOIN worktime w ON e.id = w.employee_id
                                        WHERE w.date = "' . $date . '"');
        $stmt->execute();
        return new ArrayCollection($stmt->fetchAll());
//        return new ArrayCollection($query->getResult());
    }

}
