<?php

namespace WO\OrganizerBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findByDate($date) {
        $q = $this
            ->createQueryBuilder('e')
            ->select('e')
            ->where('e.day = :date')
            ->setParameter('date', $date)
            ->getQuery();

        return new ArrayCollection($q->getResult());
    }
}
