<?php

namespace WO\OrganizerBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findByDate($date) {
        $q = $this
            ->createQueryBuilder('e')
            ->select('e')
            ->where('e.day = :date')
            ->setParameter('date', $date)
            ->getQuery();

        return new ArrayCollection($q->getResult());
    }

    /**
     * @param \DateTime $start
     * @param \DateTime $end
     * @param int $locationId
     * @return ArrayCollection
     */
    public function getAllBetweenStartAndEnd(\DateTime $start, \DateTime $end, $locationId) {
        $q = $this
            ->createQueryBuilder('e')
            ->select('e')
            ->where('e.dateStart BETWEEN :start AND :end')
            ->andWhere('e.location = :location')
            ->setParameter('start', $start->format('Y-m-d H:i:s'))
            ->setParameter('end', $end->format('Y-m-d H:i:s'))
            ->setParameter('location', $locationId)
            ->getQuery();
        return new ArrayCollection($q->getResult());
    }
}
