<?php

namespace WO\OrganizerBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * WorktimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorktimeRepository extends EntityRepository
{
    public function findAllByDate($date) {
        $q = $this
            ->createQueryBuilder('w')
            ->select('w')
            ->where('w.date = :date')
            ->setParameter('date', $date)
            ->getQuery();
        $results = new ArrayCollection($q->getResult());
        $return = array();
        foreach( $results as $result) {
//            $return[$result->getEmployee()->getId()] = array('timerange' => $result->getTimerange(),
//                                                                'worktime_id' => $result->getId(),
//                                                            'location' => $result->getLocation()
//            );
            $return[$result->getEmployee()->getId()] = $result;
        }
        return $return;
    }
}
